<%@ page contentType="text/html" pageEncoding="UTF-8" %>
<%@ page import = "java.sql.*" %>

<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>Database SQL Load</title>
    </head>
    <style>
        .error {
            color: red;
        }
        pre {
            color: green;
        }
    </style>
    <body>
        <h2>Database SQL Load</h2>
        <%
            /* How to customize:
             * 1. Update the database name on dbname.
             * 2. Create the list of tables, under tablenames[].
             * 3. Create the list of table definition, under tables[].
             * 4. Create the data into the above table, under data[]. 
             * 
             * If there is any problem, it will exit at the very first error.
             */
            String dbname = "sob_grup_03";
            String schema = "ROOT";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            /* this will generate database if not exist */
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/" + dbname, "root", "root");
            Statement stmt = con.createStatement();
            
            /* inserting data */
            /* you have to exclude the id autogenerated from the list of columns if you have use it. */
            String data[] = new String[]{
     
                "INSERT INTO " + schema + ".ROOM (ROOM_ID, LOCATION, ADDRESS, SIMPLE, EXTERIOR,  "
                    + "MOBLADA, PRICE, SEXE, MIN_EDAT, MAX_EDAT, FUMADOR, "
                    + "MASCOTES, DESCRIPTION, NAME, EMAIL, PHONE) VALUES (NEXT VALUE FOR Room_Gen, "
                    + "'REUS', 'Carrer', 1, 0, 1, 250, 'UNISEX', 0, 99, 1, 1, "
                    + "'Para todo el mundo',  'Pepe', 'arrendador1@mail.org', '+32654987321')", 
                "INSERT INTO " + schema + ".ROOM (ROOM_ID, LOCATION, ADDRESS, SIMPLE, EXTERIOR,  "
                    + "MOBLADA, PRICE, SEXE, MIN_EDAT, MAX_EDAT, FUMADOR, "
                    + "MASCOTES, DESCRIPTION, NAME, EMAIL, PHONE) VALUES (NEXT VALUE FOR Room_Gen, "
                    + "'Tarragona', 'Plaça', 1, 0, 1, 300, 'DONA', 0, 99, 1, 1, "
                    + "'Només dones',  'Susana', 'arrendador2@mail.org', '+32654321987')", 
                "INSERT INTO " + schema + ".ROOM (ROOM_ID, LOCATION, ADDRESS, SIMPLE, EXTERIOR,  "
                    + "MOBLADA, PRICE, SEXE, MIN_EDAT, MAX_EDAT, FUMADOR, "
                    + "MASCOTES, DESCRIPTION, NAME, EMAIL, PHONE) VALUES (NEXT VALUE FOR Room_Gen, "
                    + "'REUS', 'Avinguda', 1, 0, 1, 350, 'HOME', 0, 99, 1, 0, "
                    + "'Homes fumadors',  'Pepe', 'mail@mail.org', '+32654987321')", 
                "INSERT INTO " + schema + ".ROOM (ROOM_ID, LOCATION, ADDRESS, SIMPLE, EXTERIOR,  "
                    + "MOBLADA, PRICE, SEXE, MIN_EDAT, MAX_EDAT, FUMADOR, "
                    + "MASCOTES, DESCRIPTION, NAME, EMAIL, PHONE) VALUES (NEXT VALUE FOR Room_Gen, "
                    + "'BARCELONA', 'Playja', 1, 0, 1, 175, 'DONA', 0, 99, 1, 1, "
                    + "'Dones no fumadores. Pot mascotes',  'Pepe', 'arrendador1@mail.org', '+32654987321')", 
                "INSERT INTO " + schema + ".ROOM (ROOM_ID, LOCATION, ADDRESS, SIMPLE, EXTERIOR,  "
                    + "MOBLADA, PRICE, SEXE, MIN_EDAT, MAX_EDAT, FUMADOR, "
                    + "MASCOTES, DESCRIPTION, NAME, EMAIL, PHONE) VALUES (NEXT VALUE FOR Room_Gen, "
                    + "'REUS', 'Carrer', 1, 0, 1, 215, 'HOME', 0, 25, 1, 1, "
                    + "'Busco home menor de 25 sense mascotes',  'Jacob', 'arrendador3@mail.org', '+32654555521')", 
                "INSERT INTO " + schema + ".TENANT (TENANT_ID, NAME, EMAIL, PHONE, "
                    + "EDAT, SEXE, MASCOTES, FUMADOR) VALUES (NEXT VALUE FOR Tenant_Gen, 'Ada',"
                    + " 'mail1@mail.com', '+34111111111', 50, 'DONA', 0, 1)",
                "INSERT INTO " + schema + ".TENANT (TENANT_ID, NAME, EMAIL, PHONE, "
                    + "EDAT, SEXE, MASCOTES, FUMADOR) VALUES (NEXT VALUE FOR Tenant_Gen, 'Mar',"
                    + " 'mail2@mail.com', '+34222222222', 30, 'DONA', 0, 0)",
                "INSERT INTO " + schema + ".TENANT (TENANT_ID, NAME, EMAIL, PHONE, "
                    + "EDAT, SEXE, MASCOTES, FUMADOR) VALUES (NEXT VALUE FOR Tenant_Gen, 'Karim',"
                    + " 'mail3@mail.com', '+34333333333', 47, 'HOME', 1, 1)",
                "INSERT INTO " + schema + ".TENANT (TENANT_ID, NAME, EMAIL, PHONE, "
                    + "EDAT, SEXE, MASCOTES, FUMADOR) VALUES (NEXT VALUE FOR Tenant_Gen, 'Moha',"
                    + " 'mai4l@mail.com', '+34777666888', 19, 'HOME', 0, 1)",
                "INSERT INTO " + schema + ".TENANT (TENANT_ID, NAME, EMAIL, PHONE, "
                    + "EDAT, SEXE, MASCOTES, FUMADOR) VALUES (NEXT VALUE FOR Tenant_Gen, 'Pau',"
                    + " 'mail5@mail.com', '+34555555555', 23, 'HOME', 0, 0)",
                "INSERT INTO " + schema + ".USERS (USERNAME, HASH_CODE) VALUES ('sob', 'sob')"
            };
            for (String datum : data) {
                if (stmt.executeUpdate(datum)<=0) {
                    out.println("<span class='error'>Error inserting data: " + datum + "</span>");
                    return;
                }
                out.println("<pre> -> " + datum + "<pre>");
            }
        %>
        <button onclick="window.location='<%=request.getSession().getServletContext().getContextPath()%>'">Go home</button>
    </body>
</html>
